### ISSUE TITLE
[JENKINS-11976] NonExistentFieldException warnings after upgrading mercurial plugin to 1.38

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/mercurial-plugin#426]
<p>After upgrading the mercurial plugin from 1.37 to 1.38, I get the following messages in the logs:</p>

<p>Dec 3, 2011 3:46:27 PM hudson.util.RobustReflectionConverter doUnmarshal<br/>
WARNING: Skipping a non-existent field forest<br/>
com.thoughtworks.xstream.converters.reflection.NonExistentFieldException: No such field hudson.plugins.mercurial.MercurialSCM.forest<br/>
at com.thoughtworks.xstream.converters.reflection.FieldDictionary.field(FieldDictionary.java:106)<br/>
at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.getFieldType(PureJavaReflectionProvider.java:152)<br/>
at hudson.util.RobustReflectionConverter.determineType(RobustReflectionConverter.java:356)<br/>
at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:229)<br/>
at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:180)<br/>
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:82)<br/>
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:63)<br/>
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:76)<br/>
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:60)<br/>
at hudson.util.RobustReflectionConverter.unmarshalField(RobustReflectionConverter.java:290)<br/>
at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:233)<br/>
at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:180)<br/>
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:82)<br/>
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:63)<br/>
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:76)<br/>
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:60)<br/>
at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:137)<br/>
at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:33)<br/>
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:926)<br/>
at hudson.util.XStream2.unmarshal(XStream2.java:91)<br/>
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:912)<br/>
at com.thoughtworks.xstream.XStream.fromXML(XStream.java:864)<br/>
at hudson.XmlFile.read(XmlFile.java:133)<br/>
at hudson.model.Items.load(Items.java:114)<br/>
at jenkins.model.Jenkins$14.run(Jenkins.java:2357)<br/>
at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:146)<br/>
at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:259)<br/>
at jenkins.model.Jenkins$5.runTask(Jenkins.java:798)<br/>
at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:187)<br/>
at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)<br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)<br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)<br/>
at java.lang.Thread.run(Thread.java:680)</p>

---
<details><summary><i>Originally reported by <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/davidmc24.png" title="davidmc24's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=davidmc24">davidmc24</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-11976" target="_blank">NonExistentFieldException warnings after upgrading mercurial plugin to 1.38</a></i></summary>
<i><ul>
<li><b>assignee</b>: <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/davidmc24.png" title="davidmc24's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=davidmc24">davidmc24</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>component(s)</b>: mercurial-plugin
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2011-12-03T22:14:00+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 1
<li><b>imported</b>: 20251216-225446
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>After upgrading the mercurial plugin from 1.37 to 1.38, I get the following messages in the logs:</p>

<p>Dec 3, 2011 3:46:27 PM hudson.util.RobustReflectionConverter doUnmarshal
WARNING: Skipping a non-existent field forest
com.thoughtworks.xstream.converters.reflection.NonExistentFieldException: No such field hudson.plugins.mercurial.MercurialSCM.forest
        at com.thoughtworks.xstream.converters.reflection.FieldDictionary.field(FieldDictionary.java:106)
        at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.getFieldType(PureJavaReflectionProvider.java:152)
        at hudson.util.RobustReflectionConverter.determineType(RobustReflectionConverter.java:356)
        at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:229)
        at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:180)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:82)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:63)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:76)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:60)
        at hudson.util.RobustReflectionConverter.unmarshalField(RobustReflectionConverter.java:290)
        at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:233)
        at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:180)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:82)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:63)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:76)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:60)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:137)
        at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:33)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:926)
        at hudson.util.XStream2.unmarshal(XStream2.java:91)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:912)
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:864)
        at hudson.XmlFile.read(XmlFile.java:133)
        at hudson.model.Items.load(Items.java:114)
        at jenkins.model.Jenkins$14.run(Jenkins.java:2357)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:146)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:259)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:798)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:187)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:680)</p></pre>
</details>
</details>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/davidmc24.png" title="davidmc24's avatar" /> davidmc24:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-11976?focusedId=156282&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-156282">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>If you encounter this issue, when you go to Manage Jenkins, you should get a warning "You have data stored in an older format and/or unreadable data."  You can then use the Manage button provided to remove the old data.</p>
</pre>
</details>

</ul>
</details>

<p>If you encounter this issue, when you go to Manage Jenkins, you should get a warning "You have data stored in an older format and/or unreadable data."  You can then use the Manage button provided to remove the old data.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/scm_issue_link.png" title="scm_issue_link's avatar" /> scm_issue_link:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-11976?focusedId=156283&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-156283">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Code changed in jenkins
User: David M. Carr
Path:
 src/main/java/hudson/plugins/mercurial/MercurialInstallation.java
 src/main/java/hudson/plugins/mercurial/MercurialSCM.java
<a href="http://jenkins-ci.org/commit/mercurial-plugin/c9efe32683f19e0180e5806762b63998fabbc0bf" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/mercurial-plugin/c9efe32683f19e0180e5806762b63998fabbc0bf</a>
Log:
  <span class="error">&#91;FIXED JENKINS-11976&#93;</span> Add forest-related fields back for de-serialization compatibility</p>


</pre>
</details>

</ul>
</details>

<p>Code changed in jenkins<br/>
User: David M. Carr<br/>
Path:<br/>
 src/main/java/hudson/plugins/mercurial/MercurialInstallation.java<br/>
 src/main/java/hudson/plugins/mercurial/MercurialSCM.java<br/>
<a href="http://jenkins-ci.org/commit/mercurial-plugin/c9efe32683f19e0180e5806762b63998fabbc0bf" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/mercurial-plugin/c9efe32683f19e0180e5806762b63998fabbc0bf</a><br/>
Log:<br/>
  <span class="error">&#91;FIXED <a class="jira-plain-text-key" href="https://issue-redirect.jenkins.io/issue/11976">JENKINS-11976</a>&#93;</span> Add forest-related fields back for de-serialization compatibility</p>
