### ISSUE TITLE
[JENKINS-4972] Ignore merge changesets when filtering by module for polling

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/mercurial-plugin#370]
<p>If you configure a job with a module list, polling should not trigger a build<br/>
just because an incoming merge changeset mentions a file contained in one of the<br/>
modules. The list of files "modified" by a merge changeset in Mercurial is<br/>
generally meaningless (which is why it is not displayed in the changelog page);<br/>
someone merging changes made to an old parent rev with a new head will often<br/>
produce a merge that claims to "modify" completely unrelated files which were in<br/>
fact changed by other people in the other branch.</p>

<p>(The "modified files" list for a merge changeset will always include files that<br/>
were actually merged, but often includes other files that were simply picked up<br/>
as-is from one or the other parent. The exact behavior seems to be a deep<br/>
implementation detail of Mercurial with little significance to the SCM user.)</p>

<p>Example: <a href="http://deadlock.netbeans.org/hudson/job/javacard/10/changes" class="external-link" target="_blank" rel="nofollow noopener">http://deadlock.netbeans.org/hudson/job/javacard/10/changes</a> shows only<br/>
<a href="http://hg.netbeans.org/main/rev/c487f4093cf5" class="external-link" target="_blank" rel="nofollow noopener">http://hg.netbeans.org/main/rev/c487f4093cf5</a> which was a routine merge made by<br/>
someone not working on javacard.* modules. The build therefore ran even though<br/>
no changes were made to any files matching the javacard.* pattern.</p>

<p>Even if the merge is nontrivial (i.e. required conflict resolution of some<br/>
kind), and some of the resolved files were in the module list, it is very likely<br/>
that it is one merge parent is a descendant of some regular changeset which<br/>
modified those same files. Since the Hg plugin only deals with a single branch<br/>
for a given job, either that regular changeset was already in a previous build,<br/>
or it is coming it for the first time in this build - which would trigger a new<br/>
build from the polling anyway.</p>

<p>The only scenario I can think of where suppressing the file list for merge<br/>
changesets would cause a build to not be triggered by polling when it really<br/>
should be triggered (i.e. a pull & update will really cause some files in the<br/>
module list to be changed relative to the previous build) is as follows: you<br/>
modify file A in one changeset "a", modify B in another changeset "b", merge "a"<br/>
and "b", modify another file "C" (even though there was no line-level conflict<br/>
in it), commit the merge as changeset "c", finally push to a repo where some<br/>
Hudson job is listening for changes in "C" only. This seems like a very unlikely<br/>
scenario: most file edits in a merge are done only to resolve "hard" conflicts.<br/>
Once in a blue moon you might modify some file closely related to one that was<br/>
merged to avoid a semantic conflict (such as compilation error), but this is<br/>
likely to be in the same module. Anyway most of the time you would only notice<br/>
such conflicts to begin with, fixing them as a regular changeset, because a<br/>
Hudson build failed - so polling based on merges would not be helpful.</p>

---
<details><summary><i>Originally reported by <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/jglick.png" title="jglick's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jglick">jglick</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-4972" target="_blank">Ignore merge changesets when filtering by module for polling</a></i></summary>
<i><ul>
<li><b>assignee</b>: <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/jglick.png" title="jglick's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jglick">jglick</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>component(s)</b>: mercurial-plugin
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2009-11-30T12:33:33+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 0
<li><b>imported</b>: 20251216-225446
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>If you configure a job with a module list, polling should not trigger a build
just because an incoming merge changeset mentions a file contained in one of the
modules. The list of files "modified" by a merge changeset in Mercurial is
generally meaningless (which is why it is not displayed in the changelog page);
someone merging changes made to an old parent rev with a new head will often
produce a merge that claims to "modify" completely unrelated files which were in
fact changed by other people in the other branch.</p>

<p>(The "modified files" list for a merge changeset will always include files that
were actually merged, but often includes other files that were simply picked up
as-is from one or the other parent. The exact behavior seems to be a deep
implementation detail of Mercurial with little significance to the SCM user.)</p>

<p>Example: <a href="http://deadlock.netbeans.org/hudson/job/javacard/10/changes" class="external-link" target="_blank" rel="nofollow noopener">http://deadlock.netbeans.org/hudson/job/javacard/10/changes</a> shows only
<a href="http://hg.netbeans.org/main/rev/c487f4093cf5" class="external-link" target="_blank" rel="nofollow noopener">http://hg.netbeans.org/main/rev/c487f4093cf5</a> which was a routine merge made by
someone not working on javacard.* modules. The build therefore ran even though
no changes were made to any files matching the javacard.* pattern.</p>

<p>Even if the merge is nontrivial (i.e. required conflict resolution of some
kind), and some of the resolved files were in the module list, it is very likely
that it is one merge parent is a descendant of some regular changeset which
modified those same files. Since the Hg plugin only deals with a single branch
for a given job, either that regular changeset was already in a previous build,
or it is coming it for the first time in this build - which would trigger a new
build from the polling anyway.</p>

<p>The only scenario I can think of where suppressing the file list for merge
changesets would cause a build to not be triggered by polling when it really
should be triggered (i.e. a pull &amp; update will really cause some files in the
module list to be changed relative to the previous build) is as follows: you
modify file A in one changeset "a", modify B in another changeset "b", merge "a"
and "b", modify another file "C" (even though there was no line-level conflict
in it), commit the merge as changeset "c", finally push to a repo where some
Hudson job is listening for changes in "C" only. This seems like a very unlikely
scenario: most file edits in a merge are done only to resolve "hard" conflicts.
Once in a blue moon you might modify some file closely related to one that was
merged to avoid a semantic conflict (such as compilation error), but this is
likely to be in the same module. Anyway most of the time you would only notice
such conflicts to begin with, fixing them as a regular changeset, because a
Hudson build failed - so polling based on merges would not be helpful.</p></pre>
</details>
</details>

**Comment by jenkins-infra-bot** [comment]
<i>[Original `depends_on` from Jira: <a class="jira-relationship" href="https://issue-redirect.jenkins.io/issue/7594">JENKINS-7594</a>]</i>
